word_cloud_element <- function(){htmltools::tags$div(
  style="overflow-x: hidden;",
  htmltools::tags$canvas(id="word_cloud", class="word_cloud", width="700pt", height="200pt"),
  htmltools::tags$script("
      list = [
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2],
        ['gut', 10],
        ['schlecht', 10],
        ['gut', 8],
        ['schlecht', 8],
        ['gut', 6],
        ['schlecht', 6],
        ['gut', 4],
        ['schlecht', 4],
        ['gut', 2],
        ['schlecht', 2]
      ]

      var options = eval({
          list: list,
          gridSize: 10, // size of the grid in pixels,the larger the grid size, the bigger the gap between words.
          weightFactor: 3, // number to multiply for size of each word in the list
          fontWeight: 'bold', // 'normal', 'bold' or a callback
          // 'fontFamily': 'Times, serif', // font to use
          color: function() {
            return (['#009392','#39b185','#9ccb86','#e9e29c','#eeb479','#e88471','#cf597e'])[Math.floor(Math.random() * 7)]
          },
          shape: 'square',
          hover: '',
          click: '',
          rotateRatio: 0.5,
          rotationSteps: 2,
          wait: 20,
          // backgroundColor: '#f1f2f0',
      });

      WordCloud(document.getElementById('word_cloud'), options);
    ")
)}